---
title: "Die MultiLA Softwareplattform"
author:
  - name: "Markus Konrad"
    affil: 1
    main: true
    email: "markus.konrad@htw-berlin.de"
  - name: Maria Osipenko
    affil: 2
    main: true
    email: "osipenko@hwr-berlin.de"
  - name: Martin Spott
    affil: 1
    main: true
    email: "martin.spott@htw-berlin.de"
  - name: Andre Beinrucker
    affil: 1
    main: true
    email: "beinrucker@htw-berlin.de"
affiliation:
  - num: 1
    address: Hochschule für Technik und Wirtschaft Berlin
  - num: 2
    address: Hochschule für Wirtschaft und Recht Berlin
main_findings:
  - "Authoring Software und Learning Analytics für interaktive Lernanwendungen im Bereich Statistik und Data Science"
logoleft_name: "img/htw_logo.jpg"
logoright_name: "img/hwr_logo.png"
logocenter_name: "img/ifaf_logo.jpg"
poster_width: "841mm"
poster_height: "1189mm"
main_topsize: 0.2
main_bottomsize: 0.1
main_fontfamily: 'BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif'
font_family: 'BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif'
primary_colour: "#5faaea"
secondary_colour: "#5faaea"   # "#e5f1fb"
accent_colour: "#3eaf7c"
output: 
  posterdown::posterdown_betterport:
    css: "css/custom.css"
    self_contained: true
    pandoc_args: --mathjax
    number_sections: false
bibliography: packages.bib
link-citations: true
knit: pagedown::chrome_print
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      tidy = FALSE,
                      message = FALSE,
                      fig.align = 'center',
                      out.width = "100%")
options(knitr.table.format = "html") 
```

# Einleitung

Mittels der *MultiLA Softwareplattform* ist es möglich, web-basierte, interaktive Lernanwendungen zu entwickeln, diese den Studierenden zur Verfügung zu stellen und auf datenschutzkonformeweise Interaktionsdaten der Studierenden mit den Lernanwendungen zu sammeln sowie Experimente durchzuführen. Damit werden drei Ziele erreicht:

- Verbesserung der Lehre durch innovative, interaktive Lernanwendungen,
- Unterstützung der Forschung im Bereich Learning Analytics,
- Verbesserung der Lernanwendungen durch den aus den Daten gewonnenen Erkenntnissen.

Diese Softwareplattform wurde im Rahmen des IFAF MultiLA-Projekts an der HTW Berlin und der HWR Berlin entwickelt und steht komplett als Open Source Softwarepaket zur Verfügung.

TODOs:

- QR Code

## Features

- Erstellung interaktiver Lernanwendungen mittels *RMarkdown* oder als *Shiny*-Anwendungen
- Hoch granulare, konfigurierbare und anonyme Nachverfolgung von Benutzerinteraktionen mit den Lernanwendungen: Mausbewegungen, Klicks, Einreichen von Übungen usw.
- Unterstützung von A/B-Testexperimenten und integrierten Umfragen
- Konfigurierbare Lernanwendungen: Basisanwendungen einmal schreiben, Varianten über Konfigurationen erstellen
- Dynamische Zusammenfassungsleiste für Lernanwendungen
- Webbasierte Administrationsoberfläche zum Veröffentlichen von Lernanwendungen, Einrichten von Varianten und Experimenten sowie Herunterladen gesammelter Daten
- Datenaufbereitungs- und Analyseskripte
- Datenschutzkonforme, selbst gehostete Lösung

# Von der Lernanwendung zu Learning Analytics

## 1. Lernanwendungen erstellen

Der inhaltliche Rahmen liegt auf dem Bereich Statistik, Mathematik und Data Science. In diesem Bereich ist die Nutzung der Programmiersprache *R* sowohl unter Lehrenden als auch in den Curricula sehr ausgeprägt, weshalb zur Erstellung der Lernanwendungen *R-Markdown* in Kombination mit *RStudio* zum Einsatz kommen.

## 2. Lernanwendungen bereitstellen

TODO

## 3. Nutzungsdaten sammeln und auswerten 

TODO

# Hintergrund

## Softwarearchitektur

TODO

## Erstellte Lernanwendungen

TODO

## Erste Auswertungen

TODO


# Referenzen
